version: "3"
services:
  quotes:
    image: multi-platform/docker-quotes:0.1.0
    ports:
      - "4001:8080"
    networks:
      - multiplatform
  greetings:
    image: multi-platform/docker-greetings:0.1.0
    ports:
      - "4000:8080"
    environment:
      - SERVICES_QUOTE_URL=http://quotes:8080
    networks:
      - multiplatform
networks:
  multiplatform:
